// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: WorkerStream.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace UtisTestTask.ServiceContract {
  public static partial class WrokerIntegration
  {
    static readonly string __ServiceName = "WrokerIntegration";

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::UtisTestTask.ServiceContract.EmptyMessage> __Marshaller_EmptyMessage = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::UtisTestTask.ServiceContract.EmptyMessage.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::UtisTestTask.ServiceContract.WrokerMessage> __Marshaller_WrokerMessage = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::UtisTestTask.ServiceContract.WrokerMessage.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::UtisTestTask.ServiceContract.WorkerIdMessage> __Marshaller_WorkerIdMessage = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::UtisTestTask.ServiceContract.WorkerIdMessage.Parser));

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::UtisTestTask.ServiceContract.EmptyMessage, global::UtisTestTask.ServiceContract.WrokerMessage> __Method_GetWorkerStream = new grpc::Method<global::UtisTestTask.ServiceContract.EmptyMessage, global::UtisTestTask.ServiceContract.WrokerMessage>(
        grpc::MethodType.ServerStreaming,
        __ServiceName,
        "GetWorkerStream",
        __Marshaller_EmptyMessage,
        __Marshaller_WrokerMessage);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::UtisTestTask.ServiceContract.WorkerIdMessage, global::UtisTestTask.ServiceContract.WrokerMessage> __Method_GetWorkerById = new grpc::Method<global::UtisTestTask.ServiceContract.WorkerIdMessage, global::UtisTestTask.ServiceContract.WrokerMessage>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetWorkerById",
        __Marshaller_WorkerIdMessage,
        __Marshaller_WrokerMessage);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::UtisTestTask.ServiceContract.WorkerIdMessage, global::UtisTestTask.ServiceContract.WrokerMessage> __Method_DeleteWorkerById = new grpc::Method<global::UtisTestTask.ServiceContract.WorkerIdMessage, global::UtisTestTask.ServiceContract.WrokerMessage>(
        grpc::MethodType.Unary,
        __ServiceName,
        "DeleteWorkerById",
        __Marshaller_WorkerIdMessage,
        __Marshaller_WrokerMessage);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::UtisTestTask.ServiceContract.WrokerMessage, global::UtisTestTask.ServiceContract.WrokerMessage> __Method_AddOrUpdateWorker = new grpc::Method<global::UtisTestTask.ServiceContract.WrokerMessage, global::UtisTestTask.ServiceContract.WrokerMessage>(
        grpc::MethodType.Unary,
        __ServiceName,
        "AddOrUpdateWorker",
        __Marshaller_WrokerMessage,
        __Marshaller_WrokerMessage);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::UtisTestTask.ServiceContract.WorkerStreamReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of WrokerIntegration</summary>
    [grpc::BindServiceMethod(typeof(WrokerIntegration), "BindService")]
    public abstract partial class WrokerIntegrationBase
    {
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task GetWorkerStream(global::UtisTestTask.ServiceContract.EmptyMessage request, grpc::IServerStreamWriter<global::UtisTestTask.ServiceContract.WrokerMessage> responseStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::UtisTestTask.ServiceContract.WrokerMessage> GetWorkerById(global::UtisTestTask.ServiceContract.WorkerIdMessage request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::UtisTestTask.ServiceContract.WrokerMessage> DeleteWorkerById(global::UtisTestTask.ServiceContract.WorkerIdMessage request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::UtisTestTask.ServiceContract.WrokerMessage> AddOrUpdateWorker(global::UtisTestTask.ServiceContract.WrokerMessage request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for WrokerIntegration</summary>
    public partial class WrokerIntegrationClient : grpc::ClientBase<WrokerIntegrationClient>
    {
      /// <summary>Creates a new client for WrokerIntegration</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public WrokerIntegrationClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for WrokerIntegration that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public WrokerIntegrationClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected WrokerIntegrationClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected WrokerIntegrationClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncServerStreamingCall<global::UtisTestTask.ServiceContract.WrokerMessage> GetWorkerStream(global::UtisTestTask.ServiceContract.EmptyMessage request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetWorkerStream(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncServerStreamingCall<global::UtisTestTask.ServiceContract.WrokerMessage> GetWorkerStream(global::UtisTestTask.ServiceContract.EmptyMessage request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncServerStreamingCall(__Method_GetWorkerStream, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::UtisTestTask.ServiceContract.WrokerMessage GetWorkerById(global::UtisTestTask.ServiceContract.WorkerIdMessage request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetWorkerById(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::UtisTestTask.ServiceContract.WrokerMessage GetWorkerById(global::UtisTestTask.ServiceContract.WorkerIdMessage request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetWorkerById, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::UtisTestTask.ServiceContract.WrokerMessage> GetWorkerByIdAsync(global::UtisTestTask.ServiceContract.WorkerIdMessage request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetWorkerByIdAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::UtisTestTask.ServiceContract.WrokerMessage> GetWorkerByIdAsync(global::UtisTestTask.ServiceContract.WorkerIdMessage request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetWorkerById, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::UtisTestTask.ServiceContract.WrokerMessage DeleteWorkerById(global::UtisTestTask.ServiceContract.WorkerIdMessage request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return DeleteWorkerById(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::UtisTestTask.ServiceContract.WrokerMessage DeleteWorkerById(global::UtisTestTask.ServiceContract.WorkerIdMessage request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_DeleteWorkerById, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::UtisTestTask.ServiceContract.WrokerMessage> DeleteWorkerByIdAsync(global::UtisTestTask.ServiceContract.WorkerIdMessage request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return DeleteWorkerByIdAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::UtisTestTask.ServiceContract.WrokerMessage> DeleteWorkerByIdAsync(global::UtisTestTask.ServiceContract.WorkerIdMessage request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_DeleteWorkerById, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::UtisTestTask.ServiceContract.WrokerMessage AddOrUpdateWorker(global::UtisTestTask.ServiceContract.WrokerMessage request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return AddOrUpdateWorker(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::UtisTestTask.ServiceContract.WrokerMessage AddOrUpdateWorker(global::UtisTestTask.ServiceContract.WrokerMessage request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_AddOrUpdateWorker, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::UtisTestTask.ServiceContract.WrokerMessage> AddOrUpdateWorkerAsync(global::UtisTestTask.ServiceContract.WrokerMessage request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return AddOrUpdateWorkerAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::UtisTestTask.ServiceContract.WrokerMessage> AddOrUpdateWorkerAsync(global::UtisTestTask.ServiceContract.WrokerMessage request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_AddOrUpdateWorker, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected override WrokerIntegrationClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new WrokerIntegrationClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static grpc::ServerServiceDefinition BindService(WrokerIntegrationBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_GetWorkerStream, serviceImpl.GetWorkerStream)
          .AddMethod(__Method_GetWorkerById, serviceImpl.GetWorkerById)
          .AddMethod(__Method_DeleteWorkerById, serviceImpl.DeleteWorkerById)
          .AddMethod(__Method_AddOrUpdateWorker, serviceImpl.AddOrUpdateWorker).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the  service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static void BindService(grpc::ServiceBinderBase serviceBinder, WrokerIntegrationBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_GetWorkerStream, serviceImpl == null ? null : new grpc::ServerStreamingServerMethod<global::UtisTestTask.ServiceContract.EmptyMessage, global::UtisTestTask.ServiceContract.WrokerMessage>(serviceImpl.GetWorkerStream));
      serviceBinder.AddMethod(__Method_GetWorkerById, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::UtisTestTask.ServiceContract.WorkerIdMessage, global::UtisTestTask.ServiceContract.WrokerMessage>(serviceImpl.GetWorkerById));
      serviceBinder.AddMethod(__Method_DeleteWorkerById, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::UtisTestTask.ServiceContract.WorkerIdMessage, global::UtisTestTask.ServiceContract.WrokerMessage>(serviceImpl.DeleteWorkerById));
      serviceBinder.AddMethod(__Method_AddOrUpdateWorker, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::UtisTestTask.ServiceContract.WrokerMessage, global::UtisTestTask.ServiceContract.WrokerMessage>(serviceImpl.AddOrUpdateWorker));
    }

  }
}
#endregion
